apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: webapp
spec:
  serviceName: "webapp"
  replicas: 1
  template:
    metadata:
      labels:
        app: "webapp"
    spec:
      hostNetwork: true
      containers:
        - name: "webapp"
          image: "gcr.io/simpl-js/webapp"
          env:
            - name: DATA_DIR
              value: /data/db
          volumeMounts:
            - name: app-storage-mount
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: app-storage-mount
      annotations:
        volume.beta.kubernetes.io/storage-class: "app-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: app-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
