apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "webapp"
  namespace: "default"
  labels:
    app: "webapp"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "webapp"
  template:
    metadata:
      labels:
        app: "webapp"
    spec:
      hostNetwork: true
      containers:
      - name: "webapp"
        image: "gcr.io/simpl-js/webapp"